service: step-functions-demo

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-step-functions
  - serverless-step-functions-local
  - serverless-offline-lambda
  - serverless-offline

custom:
  stepFunctionsLocal:
    accountId: 101010101010
    region: us-east-1
    location: ./
    TaskResourceMapping:
      FirstState: arn:aws:lambda:us-east-1:101010101010:function:handler1
      FinalState: arn:aws:lambda:us-east-1:101010101010:function:handler2
      DefaultState: arn:aws:lambda:us-east-1:101010101010:function:handler3

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 30
  region: us-east-1
  stage: dev

functions:
  handler1:
    handler: src/handler1.endpoint
  handler2:
    handler: src/handler2.endpoint
  handler3:
    handler: src/handler3.endpoint

stepFunctions:
  stateMachines:
    Machine:
      definition:
        StartAt: FirstState
        States:
          FirstState:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:101010101010:function:handler1
            Next: wait_using_seconds
            Retry:
              - ErrorEquals: [Error]
                MaxAttempts: 0
              - ErrorEquals: [States.ALL]
                MaxAttempts: 3
            Catch:
              - ErrorEquals: [Error]
                Next: DefaultState
          wait_using_seconds:
            Type: Wait
            Seconds: 2
            Next: FinalState
          FinalState:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:101010101010:function:handler2
            End: true
          DefaultState:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:101010101010:function:handler3
            End: true
